$(document).ready(function(){
    $('.owl-carousel').owlCarousel({
        loop:true,
        nav:true,
        stagePadding: 50,
        autoplay:true,
        autoplayTimeout:1200,
        autoplayHoverPause:true,
        responsive:{
            0:{
                items:1
            },
            800:{
                items:2
            },
            1000:{
                items:3
            }
        }
    })
  });
